#!/bin/sh
#
# Write the three env files this stack runs on. Once, before the first `docker compose up`.
#
#   ./bootstrap.sh https://arlo.example.com you@example.com
#
# The two arguments are the only things this cannot invent: the address the instance answers
# on, and the first administrator's email. Everything secret is generated here — four
# database passwords, a JWT secret, a service-role key and the encryption key.
#
# Three files, because a container should be handed what it needs and nothing else:
#
#   .env        the app's. Model keys, connector credentials, the encryption key.
#   db.env      Postgres's. Four passwords, and no reason to know anything else.
#   auth.env    GoTrue's. The JWT secret it shares with the app, and its own settings.
#
# All three at mode 600, and all three ignored by git. They are the only place any of these
# values exists.
#
# What this does not write is a model key. Arlo runs without one: retrieval falls back to
# Postgres full-text search and the bot declines to answer rather than guessing. Put an
# OpenRouter key in .env afterwards and restart to turn the answering on.
#
# Re-running is refused rather than handled. Rerolling SECRET_KEY makes every connector
# token already stored unreadable, and rerolling the database passwords leaves the roles in
# the existing volume disagreeing with the URLs that reach them — neither failure says what
# it is at the point it happens.
set -eu
cd "$(dirname "$0")"

PUBLIC_URL=${1:-}
ADMIN_EMAILS=${2:-}

if [ -z "$PUBLIC_URL" ] || [ -z "$ADMIN_EMAILS" ]; then
  echo "usage: ./bootstrap.sh <public-url> <admin-email>"
  echo "   eg: ./bootstrap.sh https://arlo.example.com you@example.com"
  exit 2
fi

case "$PUBLIC_URL" in
  http://*|https://*) ;;
  *) echo "PUBLIC_URL must start with http:// or https:// — it is what OAuth redirects and"
     echo "webhook addresses are built from, and a bare hostname produces neither."; exit 2 ;;
esac
# A trailing slash ends up doubled in every URL built from this.
PUBLIC_URL=${PUBLIC_URL%/}

for f in .env db.env auth.env; do
  [ -e "$f" ] && {
    echo "deploy/selfhost/$f already exists — refusing to overwrite it."
    echo "Delete all three only if you mean to reroll every secret in them, and understand"
    echo "that doing so makes stored connector tokens unreadable and orphans the database"
    echo "volume (docker compose down -v)."
    exit 1
  }
done

command -v openssl >/dev/null || { echo "openssl is required (it mints the keys below)"; exit 1; }

# 32 bytes of hex. Hex on purpose: a base64 secret that happened to contain a $ would be
# mangled by anything that interpolates one of these files, and finding that out costs an
# afternoon.
rand() { openssl rand -hex 32; }

POSTGRES_PASSWORD=$(rand)
OWNER_PASSWORD=$(rand)
APP_PASSWORD=$(rand)
AUTH_DB_PASSWORD=$(rand)
JWT_SECRET=$(rand)
SECRET_KEY=$(rand)

# The address GoTrue is reached at, inside the compose network. Server-side only: no browser
# ever resolves this name, which is why it is not the public one.
SUPABASE_URL=http://authgw:8000

# ---------------------------------------------------------------- the service-role key
#
# On a hosted project Supabase issues this. Here it is what it has always been: a JWT signed
# with the same secret GoTrue verifies with, carrying the one role named in
# GOTRUE_JWT_ADMIN_ROLES. supabase-js sends it as both `apikey` and `Authorization`.
#
# Ten years. It is a deployment credential for a machine, and a key that quietly expires in
# a month is an afternoon nobody gets back.
b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }
jwt_header=$(printf '%s' '{"alg":"HS256","typ":"JWT"}' | b64url)
jwt_payload=$(printf '{"role":"service_role","iss":"arlo","iat":%s,"exp":%s}' \
  "$(date +%s)" "$(( $(date +%s) + 315360000 ))" | b64url)
jwt_sig=$(printf '%s.%s' "$jwt_header" "$jwt_payload" \
  | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | b64url)
SERVICE_KEY="$jwt_header.$jwt_payload.$jwt_sig"

# umask before the files exist, not chmod after them. Between those two is a window in which
# every secret below is world-readable.
umask 077

# ---------------------------------------------------------------- db.env
cat > db.env <<ENV
# Postgres's environment. Generated by deploy/selfhost/bootstrap.sh — never commit this.
#
# The three role passwords are read once, by init-passwords.sh, on the first boot of an
# empty data directory: they replace the ones setup/00-roles.sql commits in git. Changing
# them here later changes nothing — the roles already exist in the volume.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
OWNER_DB_PASSWORD=$OWNER_PASSWORD
APP_DB_PASSWORD=$APP_PASSWORD
AUTH_DB_PASSWORD=$AUTH_DB_PASSWORD
ENV

# ---------------------------------------------------------------- auth.env
cat > auth.env <<ENV
# GoTrue's environment. Generated by deploy/selfhost/bootstrap.sh — never commit this.
#
# GOTRUE_JWT_SECRET, GOTRUE_JWT_ISSUER and the audience have to agree with the app's .env
# exactly. src/server/supabase.ts verifies tokens locally — HS256 against
# SUPABASE_JWT_SECRET, issuer pinned to \${SUPABASE_URL}/auth/v1, role and aud both required
# to be \`authenticated\` — and returns null for every kind of bad. A mismatch here is not an
# error anywhere; it is "nobody is signed in", for good.
GOTRUE_API_HOST=0.0.0.0
GOTRUE_API_PORT=9999
GOTRUE_DB_DRIVER=postgres
GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:$AUTH_DB_PASSWORD@db:5432/postgres
GOTRUE_JWT_SECRET=$JWT_SECRET
GOTRUE_JWT_ISSUER=$SUPABASE_URL/auth/v1
GOTRUE_JWT_AUD=authenticated
GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
# Which role claim may use /admin/*. The service-role key in .env carries exactly this one,
# and the app creates every account through that API.
GOTRUE_JWT_ADMIN_ROLES=service_role
GOTRUE_JWT_EXP=3600
API_EXTERNAL_URL=$SUPABASE_URL
GOTRUE_SITE_URL=$PUBLIC_URL
GOTRUE_URI_ALLOW_LIST=$PUBLIC_URL/*
# The app gates account creation on registration codes and does it through the admin API.
# GoTrue's own public /signup is a second door onto the same house with none of those checks
# on it, so it stays shut.
GOTRUE_DISABLE_SIGNUP=true
GOTRUE_EXTERNAL_EMAIL_ENABLED=true
# With no SMTP configured, an account would wait forever for a confirmation mail nothing is
# going to send, so accounts are confirmed as they are created.
GOTRUE_MAILER_AUTOCONFIRM=true
#
# The SMTP block is commented out rather than left blank, and that is not tidiness. GoTrue
# parses GOTRUE_SMTP_PORT as an integer at startup and an empty string is not one:
#
#   Failed to load configuration: assigning GOTRUE_SMTP_PORT to Port:
#   converting '' to type int
#
# — fatal, in a restart loop, before it ever reaches the database. Unset is fine; empty is
# not. Uncomment all five, fill them in, and set GOTRUE_MAILER_AUTOCONFIRM=false above to
# have real confirmation mail sent.
#GOTRUE_SMTP_HOST=smtp.example.com
#GOTRUE_SMTP_PORT=587
#GOTRUE_SMTP_USER=
#GOTRUE_SMTP_PASS=
#GOTRUE_SMTP_ADMIN_EMAIL=arlo@example.com
ENV

# ---------------------------------------------------------------- .env
cat > .env <<ENV
# Arlo's environment. Generated by deploy/selfhost/bootstrap.sh — never commit this.

# ---------------------------------------------------------------- database
# Host \`db\`, resolved inside the compose network. With no DATABASE_CA_CERT,
# src/server/db.ts connects in plaintext, which is right for two containers on a private
# network and is what it already does against a local Postgres.
DATABASE_URL=postgresql://arlo_app:$APP_PASSWORD@db:5432/postgres
DATABASE_URL_OWNER=postgresql://arlo_owner:$OWNER_PASSWORD@db:5432/postgres
DATABASE_CA_CERT=
DATABASE_SCHEMA=arlo
DATABASE_POOL=10

# ---------------------------------------------------------------- identity
# The nginx in front of GoTrue. Server-side only — no browser ever resolves this name.
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
# Set, which is what puts verifyToken() on the HS256 path and means no JWKS fetch. The same
# value as GOTRUE_JWT_SECRET in auth.env, and it has to stay that way.
SUPABASE_JWT_SECRET=$JWT_SECRET

# ---------------------------------------------------------------- models
# Optional, and the product is honest without them: with no key, retrieval falls back to
# Postgres full-text search and the bot says it cannot answer rather than inventing one.
# OpenRouter serves embeddings on the same key as chat, which is why the address below is
# filled in and the second key is not.
OPENROUTER_API_KEY=
OPENROUTER_MODEL=openai/gpt-4.1-mini
EMBEDDINGS_URL=https://openrouter.ai/api/v1/embeddings
EMBEDDINGS_KEY=
EMBEDDINGS_MODEL=openai/text-embedding-3-small
EMBEDDINGS_DIMS=
BRAVE_SEARCH_KEY=

# ---------------------------------------------------------------- secrets
# Every connector token in the database is encrypted with this. Losing it does not lose the
# rows, it loses the ability to read them — back it up wherever you back up the database.
SECRET_KEY=$SECRET_KEY
# Who may reach /admin. The first account you create should be one of these.
ADMIN_EMAILS=$ADMIN_EMAILS

# ---------------------------------------------------------------- channels
# Each is a registration you make yourself, against your own instance's address. Blank is a
# channel that is simply off; nothing here has to be filled in to run the bot on the web
# widget or on Telegram.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
OUTLOOK_CLIENT_ID=
OUTLOOK_CLIENT_SECRET=
FB_APP_ID=
FB_APP_SECRET=
FB_VERIFY_TOKEN=
INSTAGRAM_APP_ID=
INSTAGRAM_APP_SECRET=
INSTAGRAM_VERIFY_TOKEN=
TIKTOK_CLIENT_KEY=
TIKTOK_CLIENT_SECRET=

# ---------------------------------------------------------------- this instance
# What OAuth redirects, webhook addresses and the widget snippet are built from. It has to
# be the address a browser actually reaches, scheme included.
PUBLIC_URL=$PUBLIC_URL
# How often the mail poller and Telegram's long poll run. Zero disables both.
POLL_SECONDS=60
# Two is plenty until traffic says otherwise; almost everything a request waits on is I/O,
# and the real ceiling is DATABASE_POOL above.
WEB_WORKERS=2
# Inside the container, on the named volumes compose.yml declares.
WA_AUTH_DIR=/opt/arlo/.wa-auth
OCR_CACHE_DIR=/opt/arlo/.ocr-cache
# OCR downloads a language model on first use. Blank switches reading pictures off.
OCR_LANGS=eng
OCR_MAX_PAGES=20
ENV

echo "wrote deploy/selfhost/{.env,db.env,auth.env} (mode 600)"
echo
echo "next, from this directory:"
echo "  docker compose build          # first build is a few minutes"
echo "  docker compose up -d --wait"
echo "  docker compose logs -f app"
echo
echo "Then put a TLS proxy in front of 127.0.0.1:9005 — README.md has one."
echo "Arlo answers on $PUBLIC_URL once it does."
